

create table if not exists public.alunos (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(trim(nome)) >= 3),
  email text not null unique check (position('@' in email) > 1),
  telefone text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.cursos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  carga_horaria integer not null check (carga_horaria > 0),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.matriculas (
  id bigint generated by default as identity primary key,
  aluno_id bigint not null references public.alunos(id) on delete cascade,
  curso_id bigint not null references public.cursos(id) on delete cascade,
  status text not null default 'ativa' check (status in ('ativa', 'concluida', 'cancelada')),
  data_matricula date not null default current_date,
  unique (aluno_id, curso_id)
);

insert into public.alunos (nome, email, telefone)
values
  ('Lucas Alves', 'lucas.alves@example.com', '(11) 94265-1081'),
  ('Gustavo Garcia', 'gustavo.garcia@example.com', '(11) 96478-0422'),
  ('Flavio Morata', 'flavio.morata@example.com', '(21) 94588-3201')
on conflict (email) do nothing;

insert into public.cursos (nome, descricao, carga_horaria)
values
  ('Introdução ao Desenvolvimento Web', 'HTML, CSS e JavaScript.', 40),
  ('Banco de Dados PostgreSQL', 'Modelagem, SQL e relacionamentos.', 30)
on conflict do nothing;


alter table public.alunos enable row level security;
alter table public.cursos enable row level security;
alter table public.matriculas enable row level security;

drop policy if exists "laboratorio_anon_select_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_insert_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_update_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_delete_alunos" on public.alunos;

create policy "laboratorio_anon_select_alunos" on public.alunos for select to anon, authenticated using (true);
create policy "laboratorio_anon_insert_alunos" on public.alunos for insert to anon, authenticated with check (true);
create policy "laboratorio_anon_update_alunos" on public.alunos for update to anon, authenticated using (true) with check (true);
create policy "laboratorio_anon_delete_alunos" on public.alunos for delete to anon, authenticated using (true);

create policy "laboratorio_anon_select_cursos" on public.cursos for select to anon, authenticated using (true);
create policy "laboratorio_anon_select_matriculas" on public.matriculas for select to anon, authenticated using (true);


select * from public.alunos order by nome;
insert into public.alunos (nome, email, telefone) values ('Teste CRUD', 'teste.crud@example.com', '0000-0000');
update public.alunos set telefone = '1111-1111' where email = 'teste.crud@example.com';
delete from public.alunos where email = 'teste.crud@example.com';


select a.nome, a.email, m.status, c.nome as curso
from public.alunos a
left join public.matriculas m on m.aluno_id = a.id
left join public.cursos c on c.id = m.curso_id
order by a.nome;
