-- ENCONTRO 02 — Supabase Auth + RLS
-- Execute depois de 01_schema_e_dados.sql no SQL Editor do Supabase.
-- Esta migração revoga as políticas anon abertas do Encontro 01.

begin;

-- Perfil público 1:1 com auth.users. O papel inicial é sempre aluno.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null default '',
  role text not null default 'aluno' check (role in ('administrador','professor','aluno')),
  criado_em timestamptz not null default now()
);

-- Turmas existentes podem permanecer sem professor até serem atribuídas.
alter table public.cursos add column if not exists professor_id uuid references public.profiles(id) on delete set null;

-- Uma matrícula agora aponta para a identidade autenticada, não para um e-mail livre.
create table if not exists public.matriculas_auth (
  id bigint generated by default as identity primary key,
  aluno_id uuid not null references public.profiles(id) on delete cascade,
  curso_id bigint not null references public.cursos(id) on delete cascade,
  status text not null default 'ativa' check (status in ('ativa','concluida','cancelada')),
  data_matricula date not null default current_date,
  unique (aluno_id, curso_id)
);

-- A função SECURITY DEFINER evita recursão de RLS ao ler o papel atual.
create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.role from public.profiles p where p.id = (select auth.uid())
$$;

revoke all on function public.current_user_role() from public;
grant execute on function public.current_user_role() to authenticated;

-- Cria perfil a partir dos metadados do signup. role nunca vem do cliente.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, nome, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(coalesce(new.email, ''), '@', 1)),
    'aluno'
  );
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public;
drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user();

-- Ative RLS nas tabelas protegidas.
alter table public.profiles enable row level security;
alter table public.alunos enable row level security;
alter table public.cursos enable row level security;
alter table public.matriculas enable row level security;
alter table public.matriculas_auth enable row level security;

-- Remove permissões permissivas do laboratório (inclusive anon).
drop policy if exists "laboratorio_anon_select_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_insert_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_update_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_delete_alunos" on public.alunos;
drop policy if exists "laboratorio_anon_select_cursos" on public.cursos;
drop policy if exists "laboratorio_anon_select_matriculas" on public.matriculas;
-- Segurança por padrão: remove outras políticas antigas que poderiam ser permissivas.
do $$
declare p record;
begin
  for p in select schemaname, tablename, policyname
           from pg_policies
           where schemaname = 'public' and tablename in ('profiles','alunos','cursos','matriculas','matriculas_auth')
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- Perfis: usuário lê o seu; administrador lê todos.
create policy profiles_select_self_or_admin on public.profiles
for select to authenticated
using (id = (select auth.uid()) or (select public.current_user_role()) = 'administrador');

-- Usuário atualiza apenas dados não privilegiados do próprio perfil, mantendo o role.
create policy profiles_update_self on public.profiles
for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()) and role = (select public.current_user_role()));

-- Administrador pode gerir outros perfis, nunca editar a si próprio por esta política.
create policy profiles_admin_manage_others on public.profiles
for all to authenticated
using ((select public.current_user_role()) = 'administrador' and id <> (select auth.uid()))
with check ((select public.current_user_role()) = 'administrador' and id <> (select auth.uid()));

-- Cursos: aluno vê apenas cursos ativos; professor vê/edita os seus; admin vê/edita todos.
create policy courses_read_by_role on public.cursos
for select to authenticated
using (
  (select public.current_user_role()) = 'administrador'
  or ((select public.current_user_role()) = 'professor' and professor_id = (select auth.uid()))
  or ((select public.current_user_role()) = 'aluno' and ativo = true)
);

create policy courses_teacher_insert_own on public.cursos
for insert to authenticated
with check (
  (select public.current_user_role()) = 'professor' and professor_id = (select auth.uid())
  or (select public.current_user_role()) = 'administrador'
);

create policy courses_teacher_update_own on public.cursos
for update to authenticated
using ((select public.current_user_role()) = 'professor' and professor_id = (select auth.uid()))
with check ((select public.current_user_role()) = 'professor' and professor_id = (select auth.uid()));

create policy courses_admin_update on public.cursos
for update to authenticated
using ((select public.current_user_role()) = 'administrador')
with check ((select public.current_user_role()) = 'administrador');

create policy courses_admin_delete on public.cursos
for delete to authenticated
using ((select public.current_user_role()) = 'administrador');

-- Matrículas antigas (ligadas a alunos legados) deixam de ser expostas pelo cliente.
-- Matrículas autenticadas: aluno vê/cria/cancela as próprias; professor acompanha cursos seus;
-- administrador tem acesso total.
create policy enrollments_read_own_teacher_admin on public.matriculas_auth
for select to authenticated
using (
  aluno_id = (select auth.uid())
  or (select public.current_user_role()) = 'administrador'
  or exists (
    select 1 from public.cursos c
    where c.id = matriculas_auth.curso_id and c.professor_id = (select auth.uid())
      and (select public.current_user_role()) = 'professor'
  )
);

create policy enrollments_student_insert_own on public.matriculas_auth
for insert to authenticated
with check (
  aluno_id = (select auth.uid())
  and (select public.current_user_role()) = 'aluno'
  and exists (select 1 from public.cursos c where c.id = curso_id and c.ativo = true)
);

create policy enrollments_student_cancel_own on public.matriculas_auth
for update to authenticated
using (aluno_id = (select auth.uid()) and (select public.current_user_role()) = 'aluno')
with check (aluno_id = (select auth.uid()) and (select public.current_user_role()) = 'aluno');

create policy enrollments_admin_manage on public.matriculas_auth
for all to authenticated
using ((select public.current_user_role()) = 'administrador')
with check ((select public.current_user_role()) = 'administrador');

-- A tabela legada public.alunos não é acessível a usuários web. Nenhuma policy = deny all.
-- Os grants abaixo complementam RLS: authenticated recebe operações somente onde policies decidem;
-- anon não recebe acesso a dados protegidos.
revoke all on public.alunos, public.matriculas from anon, authenticated;
grant select, insert, update, delete on public.profiles, public.cursos, public.matriculas_auth to authenticated;
grant usage, select on sequence public.cursos_id_seq, public.matriculas_auth_id_seq to authenticated;

commit;

-- PROMOÇÃO ADMINISTRATIVA (executar no SQL Editor como proprietário do projeto).
-- 1) Cadastre e confirme a conta pelo fluxo normal de Auth.
-- 2) Substitua o e-mail e execute UMA VEZ:
-- update public.profiles p set role = 'administrador'
-- from auth.users u where p.id = u.id and lower(u.email) = lower('admin@exemplo.com');
-- Não permita que signup envie role; o trigger força 'aluno'.
-- Atribua professores usando UPDATE profiles e UPDATE cursos no SQL Editor.
